name: Setup Go Environment
description: Setup Go and download dependencies

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.2'

    - name: Download dependencies
      run: go mod download
      shell: bash

    - name: Build binaries
      run: make build
      shell: bash
