name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: ./.github/actions/setup

      - name: Build binaries
        run: make build

      - name: Test binaries
        run: make test